/**
 * 本地存储
 */
export const LOCAL_STORAGE = {
  KEY: {
    USER_NAME: 'USER_NAME', // 用户名称
    LOGIN_USER_NAME: 'LOGIN_USER_NAME', // 登录用户名称
    USER_ID: 'USER_ID', // 用户id
    LOGIN_STATUS: 'LOGIN_STATUS', // 用户登录状态
    DATADICT: 'DATA_DICT', // 数据字典
    HCRM_DATADICT: 'HCRM_DATADICT', // hcrm 数据字典
    USER_MENUS: 'USER_MENUS', // 菜单权限
    USER_OPERATIONS: 'USER_OPERATIONS', // 操作权限
    JIAHUI_WEB_TOKEN: 'JIAHUI_WEB_TOKEN', // 登录token
    MINI_APPT_TYPE: 'MINI_APPT_TYPE' // 预约就诊类型
  }
}

export const DATADICT_KEY = {
  LANG: 'LANG', // 语言
  RESULT_CODE_CHINESE: 'RESULT_CODE_CHINESE', // 中文code返回码
  RESULT_CODE_ENGLISH: 'RESULT_CODE_ENGLISH', // 英文code返回码
  STAFF_ACCOUNT_STATE_KEY: 'STAFF_ACCOUNT_STATE_KEY', // 员工账号状态
  DEPARTMENT_LEADER_KEY: 'DEPARTMENT_LEADER_KEY', // 是否为部门leader
  AUDIT_TYPE_KEY: 'AUDIT_TYPE_KEY', // 流程分类状态KEY
  AUDIT_STATUS_KEY: 'AUDIT_STATUS_KEY', // 文章 状态KEY,
  RESOURCE_TYPE_KEY: 'RESOURCE_TYPE_KEY', // 资源类型
  PROJECT_TYPE_ENUM: 'PROJECT_TYPE_ENUM', // 项目或系统类型
  RESOURCE_MODULE_TYPE_KEY: 'RESOURCE_MODULE_TYPE_KEY', // 资源所属模块类型
  EFFECTIVE_STATE: 'EFFECTIVE_STATE', // 生效状态
  SENSITIVE_WORD_RANK: 'SENSITIVE_WORD_RANK', // 敏感词等级
  SEX: 'SEX', // 性别
  READ_TYPE: 'READ_TYPE', // 文章阅读权限
  PUSH_TYPE: 'PUSH_TYPE', // 微信推送类型
  RESERVE_STATE: 'RESERVE_STATE', // 预约状态
  WORK_STATE: 'WORK_STATE', // 在职状态
  NATIONALITY_ENUM: 'NATIONALITY_ENUM', // 国籍
  APP_SUBSCRIBE_STATUS: 'APP_SUBSCRIBE_STATUS', // 小程序预约管理状态
  CHANNEL_ACTIVITY_STATUS: 'CHANNEL_ACTIVITY_STATUS', // 推广活动上线/下线
  TELEMEDICINE_USER_GENDER_ENUM: 'TELEMEDICINE_USER_GENDER_ENUM', // 患者档案管理性别
  TELEMEDICINE_ARCHIVES_TYPE_PERMISSION_ENUM: 'TELEMEDICINE_ARCHIVES_TYPE_PERMISSION_ENUM', // 患者档案管理权限
  TELEMEDICINE_ARCHIVES_TYPE_ENUM: 'TELEMEDICINE_ARCHIVES_TYPE_ENUM', // 患者档案管理TAB
  ACCORDING_TO_STATE: 'ACCORDING_TO_STATE', // 显示/不显示
  WE_CHAT_TECHNICAL_SOLUTION_KEY: 'WE_CHAT_TECHNICAL_SOLUTION_KEY', // 技术方案
  MP_TYPE_KEY: 'MP_TYPE_KEY',
  AUTHORIZATION_WAY_KEY: 'AUTHORIZATION_WAY_KEY', // 授权方式
  CUSTOMERFROM: 'CUSTOMERFROM', // 客户渠道来源
  SYSTEM_URL: 'SYSTEM_URL'
}

export const HCRM_DATADICT_KEY = {
  MGT_CUSTOMER_FROM: 'MGT_CUSTOMER_FROM' // 客户渠道来源
}
/**
 * 类型
 * @type {{HCRM: number, JIH_WEB: number, SCRM: number}}
 */
export const PROJECT_TYPE = {
  HCRM: 1,
  JIH_WEB: 2,
  SCRM: 3
}

export const WECHAT_STATISTICS_ALERT_MESSAGE = '统计时间截止前一天24：00，即可查询最新数据日期为当前日期的前一天；日期查询支持60天内的时间跨度查询。'

export const PAGE_SIZE_OPTIONS = ['10', '20', '30', '40', '50', '100', '500', '1000']
